### PR TITLE
bug fix: added __init.py__ to parse directory

### PR DESCRIPTION
**Pull request by manu-chroma**
also, added ``def main()`` in ``wp_chat.py``

### CODE REVIEW

**Comment by manu-chroma** [comment]
I think you can safely update it on pypi also and expect it to work this time :smiley:

**Comment by nmoya** [comment]
LGTM

**Comment by nmoya** [comment]
I merged so I'm not blocked to do the upload to Pypi

**Comment by nmoya** [comment]
@manu-chroma I just uploaded to PyPi, 1.0.2 should be online.

**Pull request merged**
