### PR TITLE
Fix: Allow regexes

### PR DESCRIPTION
**Pull request by nick-merrill**
Regexes were not coming through when passing the `-r` flag. Now they do.

If I'm missing something and the `-r` flag actually does work currently, my bad.  I couldn't get it to work without this modification, and possibly there's a modification that is more in line with the flow of the code.

Thanks for putting out a helpful tool!

### CODE REVIEW

**Comment by nmoya** [comment]
@cloudrave You are absolutely right, I think it is a bug. Thank you very much for your contribution!

**Review by nmoya — APPROVED** [review]
LGTM

**Review by manu-chroma — APPROVED** [review]
LGTM! :+1:

**Comment by manu-chroma** [comment]
@cloudrave Thanks for your contribution!

**Pull request merged**
