### PR TITLE
Updated dateline and main

### PR DESCRIPTION
**Pull request by gtadiparthi**
Hi 

I made the following changes.

1. The datelib had to be changed for my whastapp as my whatsapp text had date in MM/DD/YYYY format.

2. Main.py was not reading multiple lines from the same user. So, changed it accordingly.

3. parse_whatsapp and transcript.py is a more cleaner version of the same thing. I had created these files to separate any other parsers that I might write in the future. Pull it if you find it useful.

Thanks.

### CODE REVIEW

**Comment by nmoya** [comment]
Could you add the contents of commit `f98fc8b` in a separate folder (e.g. `applications/speech`, or `demos/speech`), and a readme inside that folder that links to your blog post, just for reference? Since it adds a lot of dependencies to the code, I don't want to become confusing the source code of the repository with an application.

**Comment by nmoya** [comment]
Could you please remove commit `7a1ec2c` of the Pull Request?

**Comment by gtadiparthi** [comment]
Hi

I made the changes that you requested: removing print i and changing the indentation. You can ignore additional applications and the other pull request.

**Comment by nmoya** [comment]
@gtadiparthi I'm really sorry for being pecky, but your new commit added some files: `deactivate/include/python2.7`, `test/22_OW_MT.txt.json`, `test/34_AR_BQ.txt.json`, `transcript.py`, `parse_whatsapp.py`, which shouldn't be merged.

I can do the merge manually, but then the commit would be in my name, not yours. Ando you may be interested in open source contributions.
If you are, I recommend you do the following:
Create a branch in your local repository based in nmoya:master. 
Manually copy the content of `datelib.py` and `main.py` to this branch. Do a commit in this branch. Close this Pull Request and open another one, requesting a merge between your new branch and my master.

If you are not interested in open source contributions, let me know that I do this process manually, (but it will look like I did the change, not you, since I will be doing the commit).

Another thing, yesterday I removed the `main.py` file, since it was deprecated. So you should merge your contribution to `chat.py` file. (Which is the new main.py).

**Comment by gtadiparthi** [comment]
Hello:

Thank you for the nice email.

I will make the changes at the end of day today (20 hours later).

Thanks.

**Comment by gtadiparthi** [comment]
I will do as you say. Closing this pull request and will add another.

**Pull request closed without merging**
