### PR TITLE
pip support: add setup.py and other relevant files to the project

### PR DESCRIPTION
**Pull request by manu-chroma**
you can update the relevant fields in ``setup.py`` 
please test this to see if it works well for you. 

you can install the project by running ``python setup.py install`` and then using ``wp_chat -h`` anywhere in the virtual env (if using any)

Let me know how it works for you. I'll make changes to the docs after you confirm :)

### CODE REVIEW

**Comment by nmoya** [comment]
@manu-chroma Ops, I got distracted by a meeting and didn't see your PR. I was about to open a new one: https://github.com/nmoya/whatsapp-parser/pull/16

Is it published in PyPi already? or that's the next step?

The only difference between our PRs is the author and author email.

**Comment by nmoya** [comment]
@manu-chroma The `python setup.py install` is just to test, right?
The final goal is to do: `pip install whatsapp-parser`. and then `wp_chat -h`

is that what you had in mind?

**Comment by manu-chroma** [comment]
> The final goal is to do: pip install whatsapp-parser. and then wp_chat -h 

very true. that is just for testing purpose. there seems to be a little bug in ``setup.py`` 
I'll push a fix as soon as you merge either of the PR https://github.com/nmoya/whatsapp-parser/pull/15, https://github.com/nmoya/whatsapp-parser/pull/16

> Is it published in PyPi already? or that's the next step? 

that would be the next step. either one of us can do that

**Comment by manu-chroma** [comment]
Uploading to pypi shouldn't be a problem now 
reference: https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by nmoya** [comment]
@manu-chroma I closed my PR. Let's merge #15 

Please push the fix on setup.py

**Comment by nmoya** [comment]
@manu-chroma I'm starting the steps to upload to pypi.

**Comment by manu-chroma** [comment]
wait, I'll update this PR itself then. amend the last commit.

**Comment by nmoya** [comment]
@manu-chroma Yes, I will only do the upload when the PR is merged. Just getting ready here on my side.

**Comment by manu-chroma** [comment]
Please review and merge. I've added your credentials and also fixed minor bug in file handling

**Comment by nmoya** [comment]
@manu-chroma Thanks for adding the credentials!

**Comment by manu-chroma** [comment]
> @manu-chroma Yes, I will only do the upload when the PR is merged. Just getting ready here on my side. 

sounds good to me! :smile: I'll stick around for sometime if you plan to upload it today!

**Comment by nalbanders** [comment]
I love getting these updates. You guys are awesome ;) Happy this is evolving

**Comment by nmoya** [comment]
@manu-chroma @nalbanders Thanks for all the help guys! 21 starts in this repository! Now published in python package manager: https://pypi.python.org/pypi/whatsapp-parser/1.0.0

**Pull request merged**
